### ISSUE TITLE
[건의] 잠깐 테스트 하고, 건의사항 드립니다.

### ISSUE THREAD

**Issue by Neytiri7** [portu-sim/comfyui_bmab#1]
1. 디테일러에서 내가 원하는 디텍트 모델을 불러와서 사용할수 있었으면합니다.
 - 지금 몸, 얼굴, 손만 있는데, 의상이나, 발도 디테일링 하고 싶은데, 다른 디테일러 말고 BMAB를 사용하고 싶습니다.

2. 업스케일, 하이레스를 배율로 적용하면 좋겠습니다.
 - 가로와 세로를 번갈아 가면서, 하다보니, 매번 가로세로측 길이를 확인해서 작성해야 하니까, 불편함이 있습니다.

3. SAM 로드를 한번만 하면 좋을것 같습니다.
 - 1번 항목과 동일한데, 이미 다른 곳에서 SAM을 로더로 불러와서 사용중인데, BMAB를 사용하면, 한번 더 불러오는 경우가 되어버립니다. 그래서, 기존 SAM로더를 사용할수 있도록 해주시면 좋을것 같습니다.

잠깐 사용해보고 불편한 부분을 건의 드렸습니다.
제작 의도가 있으실텐데, 실례가 아닌가 싶습니다.

**Comment by portu-sim** [comment]
1. Detail Anything Node 추가 예정입니다.
2. 저도 불편해서 수정하려고 하는 중입니다.
3. sd-webui-BMAB 코드를 따서 하다 보니 release 자주 하도록 구조가 되어 있습니다. 속도에 더 집중하도록 하겠습니다.

**Comment by portu-sim** [comment]
1. 추가되었습니다.
2. 수정되었습니다.
3. 기존 ComfyUI SAM과 방식이 달라서 활용이 안됩니다.

**Comment by Neytiri7** [comment]
아쉽네요... 3번은 저사양에서는 어쩔수 없는 선택이라서... ㅠ.ㅠ

고사양이면, 여러개를 로드해도 상관없는데, 저사양이면, 2개 이상 로드하면, 엄청 버벅거리거든요... ㅠ.ㅠ
