### ISSUE TITLE
faceDetailer  에서 에러가 발생합니다.

### ISSUE THREAD

**Issue by JanggeunBae** [portu-sim/comfyui_bmab#11]
<img width="799" alt="erorr" src="https://github.com/portu-sim/comfyui_bmab/assets/143604221/f44d9d52-6604-4d9f-9076-70475a986702">

간단한 문제 같은데... 해결 방법을 모르겠습니다. 가르침 부탁드립니다.

**Comment by portu-sim** [comment]
수정 완료했습니다.
