### ISSUE TITLE
output 경로에 yyyy-mm-dd 폴더가 생성됩니다.

### ISSUE THREAD

**Issue by Neytiri7** [portu-sim/comfyui_bmab#16]
BMAB가 설치된 상태에서 ComfyUI를 실행하면, output 폴더 안에 "2024-05-28"의 날짜 폴더가 생성됩니다.
또, 이미지가 완성되면, 해당 폴더가 생성됩니다.

해당 폴더는 사용하지 않는데, 계속해서 생성되고,  지우고, 또 생성되고, 지우고를 반복합니다.

그리고, 세이브 노드중에서 특정 폴더로 지정할수 있는 노드의 경우,
프리뷰 이미지가 오류가 나는 경우가 확인되었습니다.

![333780424-719b3407-5e44-44ce-ab56-ea8ca4a241d5](https://github.com/portu-sim/comfyui_bmab/assets/139053327/ab7c7283-0a85-4a94-8aa2-d7049f19bc98)

bmab를 삭제하면, 해당 노드의 프리뷰도 정상적으로 표시되는것을 확인하였습니다.

사용자가 특정 폴더를 지정했지만, BMAB에서 생성된 날짜 폴더로 인해서, 저장 관련 부분이 꼬인것으로 확인되고 있습니다.

확인 부탁드립니다.

**Comment by portu-sim** [comment]
이것은  의도된 동작입니다. 프리뷰가 temp에 저장되는 것은 아닌지요?

**Comment by Neytiri7** [comment]
https://github.com/WASasquatch/was-node-suite-comfyui 이 노드의 image save라는 노드인데...
사용자가 출력 위치를 따로 정해놓은 상태에서 bmab에서 출력 위치에 날짜 폴더가 만들어지면서, 저장 경로에 대해서 꼬이는것 같더라구요. 그래서, 저렇게 프리뷰가 깨져서 표시되고 있습니다. bmab를 지우면, 또 잘 나와요~

그리고, 이게 의도된 동작이면, 사용자가 컨트롤 할 수 있나요??
저와 같이 날짜 폴더는 필요없는 분들이 있을수 있으니까요...

**Comment by portu-sim** [comment]
수정해서 원복했습니다.
