### ISSUE TITLE
IMPORT FAILED - NO BLEND MOES MODULE?

### ISSUE THREAD

**Issue by aifuzz59** [portu-sim/comfyui_bmab#18]
can you help with this error?

  File "D:\ComfyUI_tutorial\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_bmab\bmab\process.py", line 4, in <module>
    from blendmodes.blend import blendLayers, BlendType
ModuleNotFoundError: No module named 'blendmodes'

**Comment by portu-sim** [comment]
Sorry I'll add blendmodes to requrements.txt
You can fix this problem like this.
If you install ComfyUI Manager. You can install package in ComfyUI Manager

<img width="342" alt="image" src="https://github.com/portu-sim/comfyui_bmab/assets/141602933/548d1172-3b1a-4a3d-987d-f980a8956599">

then pop up dialog.
just put "blendmodes" into popup. and install.

**Comment by portu-sim** [comment]
blendmodes is in requirements. How do you install comfyui_bmab?

**Comment by aifuzz59** [comment]
I git clone from github

**Comment by portu-sim** [comment]
after clone you install dependencies. 

cd D:\ComfyUI_tutorial\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\
cd ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_bmab
D:\ComfyUI_tutorial\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\python.exe -m pip install -r requirements.txt
