### ISSUE TITLE
Error occurred when executing BMAB Subframe Hand Detailer

### ISSUE THREAD

**Issue by iordcalin** [portu-sim/comfyui_bmab#20]
Hi,I'm getting this error and don't know how to resolve it:

Error occurred when executing BMAB Subframe Hand Detailer:

The checkpoint you are trying to load has model type `grounding-dino` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.

**Comment by portu-sim** [comment]
For normal operation, transformer 4.40.0 or higher is required. You can install it with pip or through comfyui manager.
transformer >= 4.40.0

**Comment by iordcalin** [comment]
Thanks,I managed to install using the comfy ui manager install pip packages "transformers".
I recommend that you mention this in your description in case others will have this problem as well.
