### ISSUE TITLE
업스케일+고해상도 보정시 몽달귀신이 되는 경우가 간혹 있습니다.

### ISSUE THREAD

**Issue by Neytiri7** [portu-sim/comfyui_bmab#28]
![image](https://github.com/portu-sim/comfyui_bmab/assets/139053327/c164b09b-a7f8-4da1-90e5-80b700c0cd71)

이게 세팅값인데...
특정 이미지가 몽달귀신처럼 얼굴이 뭉개지더라구요.

어떤 부분에서 문제가 있는건지...
뭔가 세팅이 잘못된건지 확인 부탁드립니다.

![C_Baedari_20240610_0128451](https://github.com/portu-sim/comfyui_bmab/assets/139053327/8559c806-850f-44c4-95f7-e0844b948b58)

**Comment by portu-sim** [comment]
person detection을 정확하게 하지 못한 경우에, 지금 처럼 비스듬 한 경우, 얼굴 부분이 인물의 한 부분이라 인식하지 못하면,
뭉개질 확률이 있습니다. 이런 경우에는 person detailer를 사용하지 않는 것이 좋습니다.
