### ISSUE TITLE
If only one hand pic, the openpose Forced into both hands 

### ISSUE THREAD

**Issue by xueqing0622** [portu-sim/comfyui_bmab#30]
If only one hand pic, the openpose Forced into both hands 
![image](https://github.com/portu-sim/comfyui_bmab/assets/114840118/fd2ffc94-0e06-40ab-b198-988016bfc48f)

**Comment by portu-sim** [comment]
This seems to be due to the behavior of OpenPose Annotator. In this case, it is recommended to use BMAB Subframe Hand Detailer instead of OpenPose Detailer.
