### ISSUE TITLE
BMAB KSampler Hires. Fix 단독 사용시 seed 에러가 표시됩니다.

### ISSUE THREAD

**Issue by Neytiri7** [portu-sim/comfyui_bmab#4]
![image](https://github.com/portu-sim/comfyui-bmab/assets/139053327/2fdd0132-50b4-4fb9-afff-180fe04bf469)

!!! Exception during processing!!! 'NoneType' object has no attribute 'seed'
Traceback (most recent call last):
  File "A:\SynologyDrive\ComfyUI-webui\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\SynologyDrive\ComfyUI-webui\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\SynologyDrive\ComfyUI-webui\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\comfyui-bmab\bmab\nodes\sampler.py", line 176, in sample
    print('Hires SEED', bind.seed, bind.model)
                        ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'seed'

해당 노드는 BMAB Integrator와 같이 사용해야 하는데, 없어도 이미지가 생성이 되다보니,
단독 노드로 사용되는걸로 보입니다. 저도 그랬습니다.

이미지 생성시 시드 관련 오류 메시지가 표시되거나, 아니면, 단독으로도 사용 가능하게 seed 항목이 추가되면 좋을것 같습니다.

그리고, bmab 노드들이 bind로 묶여서 동작하다보니, 단독으로 사용이 가능한 느낌을 주고 있습니다.
차라리 BMAB Integrator 없이도 단독으로도 사용가능하게 하면 좋을것 같습니다.

**Comment by portu-sim** [comment]
BMAB Integrator가 없으면 생성 안됩니다.
Integrator 안에 모델부터 vae까지 전부 포함되어 있기 때문에 없으면 동작하지 않습니다.

**Comment by portu-sim** [comment]
뭔가 예전 것인 것 같은데 다시 노드를 만들어보시죠.

**Comment by Neytiri7** [comment]
단독 사용이 안되는걸 확인해서 종료합니다.
