### ISSUE TITLE
BMAB Person Detailer 이 항목이 BMAB KSampler Hires. Fix과 연결되면, 호스트가 강제로 끊깁니다.

### ISSUE THREAD

**Issue by Neytiri7** [portu-sim/comfyui_bmab#5]
![Screenshot 2024-05-19 at 14 47 29](https://github.com/portu-sim/comfyui-bmab/assets/139053327/3dd8abcd-ded7-49c1-91e2-84cd8fbda93b)

BMAB Person Detailer 이 항목이 앞에 있던 뒤에 있던 연결만 되면, 호스트가 강제로 끊깁니다. 동작을 안해요.

0: 640x512 (no detections), 13.4ms
Speed: 1.5ms preprocess, 13.4ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 512)
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 80, in _run
  File "asyncio\proactor_events.py", line 165, in _call_connection_lost
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

**Comment by portu-sim** [comment]
제가 만든 노드에는 steps 와 cfg라는 항목이 없습니다. 이건 뭘까요?

**Comment by portu-sim** [comment]
<img width="1370" alt="image" src="https://github.com/portu-sim/comfyui_bmab/assets/141602933/313705e3-9403-48d4-a923-51eefbd42428">

**Comment by Neytiri7** [comment]
외부 노드를 연결하려고 인풋을 따로 뺀거에요~
해당 노드에서 우클릭하시면 컨버트 위젯 인풋 항목에서 선택하시면 됩니다.

**Comment by Neytiri7** [comment]
최신 버전으로 업데이트 이후에 했더니, 정상 진행됩니다.
