### ISSUE TITLE
[건의] BMAB Integrator 항목에 Conditioning 항목이 있었으면 싶습니다.

### ISSUE THREAD

**Issue by Neytiri7** [portu-sim/comfyui_bmab#6]
현재 text는 Conditioning으로 변환되는게 있는 반면에...
Conditioning이 text로 변환되는 노드가 확인되지 않아서...

다른 노드를 연결할때, Conditioning으로 들어가지 않아서, 불편합니다.

![스크린샷 2024-05-19 135853](https://github.com/portu-sim/comfyui-bmab/assets/139053327/d79c17ae-6714-4e56-bad0-79ed4cd77e13)

![Screenshot 2024-05-19 at 14 57 12](https://github.com/portu-sim/comfyui-bmab/assets/139053327/a93b44b6-57f0-459d-8d44-7354fc86d071)

**Comment by portu-sim** [comment]
왜 프롬프트 입력창이 안나오는 것일까요?

**Comment by portu-sim** [comment]
<img width="904" alt="image" src="https://github.com/portu-sim/comfyui_bmab/assets/141602933/5f1b95e4-eb76-4daf-a727-580f1de053ee">

**Comment by Neytiri7** [comment]
![image](https://github.com/portu-sim/comfyui_bmab/assets/139053327/024cce9d-f594-4b08-be56-099a100e01cd)

ComfyUI 기본 기능중 하나입니다.
해당 노드 항목에 있는 항목을 외부에 다른 노드에서 불러올때 사용하는 방식입니다.

**Comment by portu-sim** [comment]
BMAB Extractor를 이용하면 BMAB Bind에서 conditioning을 분리할 수 있습니다.

**Comment by Neytiri7** [comment]
BMAB Integrator에서 바로 conditioning으로 받는 얘기입니다.

현재 text는 Conditioning으로 변환해주는 노드가 있는데...
그 반대로 Conditioning이 text로 변환되는 노드는 없어서...

프롬프트 노드가 Conditioning일때는 BMAB에 연결이 안됩니다.

**Comment by portu-sim** [comment]
BMAB Prompt를 쓰면 중간에 프롬프트 변경이 가능합니다.
다른 이유가 더 필요하신가요?
Conditioning을 받아봐야 Integrator에서 prompt에 의해 삭제 되어버리기 때문에 의미가 없습니다.

**Comment by Neytiri7** [comment]
방식이 다른거였군요~!!
보통 대부분 String, text보다는 Conditioning으로 보내는 노드들이 많아서요~
물론 저는 String, text 그리고, Conditioning등등 다양한 노드를 사용하고 있어서요~

그래서, 범용성이 있는 Conditioning이 더 좋지 않을까 싶었던겁니다.
다른 이유는 없습니다.
