### ISSUE TITLE
[건의] bmab Controlnet 항목의 image_file은 필수가 아닌 선택으로 하면 좋을것 같습니다.

### ISSUE THREAD

**Issue by Neytiri7** [portu-sim/comfyui_bmab#7]
단순히 컨트롤넷 기능만 사용하고 싶은데, 이미지 파일이 필수 항목이라서, 사용하고 싶지 않을 경우 어떻게 해야할지 모르겠습니다.

이미지 파일은 선택으로 외부 노드를 가지고 이미지를 불러올수 있도록 해도 좋을것 같네요.

![스크린샷 2024-05-19 135955](https://github.com/portu-sim/comfyui-bmab/assets/139053327/0850df4f-95bb-4c26-87d0-3d2c385ebcf1)

**Comment by portu-sim** [comment]
왼쪽에 이미지 파란 곳에 넣으면 image_file은 무시됩니다.
이것 이전 버전입니다. 새로 받아 보시기 바랍니다.

**Comment by Neytiri7** [comment]
업데이트 하고, none으로 한다음에 image_in에 이미지를 인풋 했지만, 사용이 되지 않습니다.
1차로 만들어진 이미지를 DWPose Estimator 노드를 통해서 오픈 포즈 이미지를 추출해서, 추출된 이미지를 기반으로 컨트롤넷으로 업스케일 및 고해상도 보정을 하려고 했지만...
동작 자체를 안합니다.

![image](https://github.com/portu-sim/comfyui_bmab/assets/139053327/338af88d-e0a0-4945-8037-a155a1fa3cc5)
