### ISSUE TITLE
새롭게 추가된 BMAB Detail Anything의 디노이즈 항목을 변경해도 사각형 프레임이 나옵니다.

### ISSUE THREAD

**Issue by Neytiri7** [portu-sim/comfyui_bmab#8]
![C20240520_0040271](https://github.com/portu-sim/comfyui_bmab/assets/139053327/0d9c238d-abd7-4ede-8ede-ae51aa218d9b)

BMAB Detail Anything를 이용해서, 디테일링을 했는데...
사각형 프레임이 사라지지 않고 그대로 표시됩니다.

![Screenshot 2024-05-20 at 00 37 16](https://github.com/portu-sim/comfyui_bmab/assets/139053327/22c3ad5b-e833-4797-b386-ea9d4831ba6e)

세팅이 이렇게 했는데, 어떻게 세팅을 해야 하는건지...
다양하게 해도 사각형 프레임이 사라지지 않습니다.

노드를 추가해야 하는건지... 아니면, 저 세팅만으로도 가능한지 확인 부탁드립니다.

**Comment by portu-sim** [comment]
디테일링이 detection -> img2img로 다시 그린 후에 그것을 원래의 위치에 가져다 두는 방식입니다.
본래 이미지에서 prompt가 달라졌다면, 이런 이미지 변화는 불가피 합니다.
모델에 따라서 denoising값에 따라서 변화 폭이 큽니다만, 이 경우는 상당히 크네요.

**Comment by portu-sim** [comment]
수정 버전 올렸습니다.

**Comment by Neytiri7** [comment]
![C20240520_0131041](https://github.com/portu-sim/comfyui_bmab/assets/139053327/ed636b6e-e3e3-4c2e-b92a-7496b7a9851d)

수정 확인 하였습니다.
